<a href="https://colab.research.google.com/github/Rohithtechis/Data-processing-Assignment/blob/main/DP_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#1) Generate an array of zeroes using inbuilt numpy function.
a=[['0','0','0'],['0','0','0']]
print(a)

[['0', '0', '0'], ['0', '0', '0']]


In [4]:
#2) Run the given code and find the dot product of both arrays.
import numpy as np
a = np.random.randint(2,10, (3,4))
b = np.random.randint(2,10, (4,3))
print(a)
print(b)
print('Dot product of the both arrays is')
a.dot(b)

[[2 8 5 9]
 [8 2 6 5]
 [5 6 5 4]]
[[5 3 8]
 [8 3 3]
 [4 2 6]
 [2 2 5]]
Dot product of the both arrays is


array([[112,  58, 115],
       [ 90,  52, 131],
       [101,  51, 108]])

In [2]:
#3)Read the csv file provided using pandas and display the first 5 entries
import pandas as pd
df=pd.read_csv('/content/data.csv')
df.head()

OBJECTID                        UNIT_NAME  ... SHAPE.AREA  SHAPE.LEN
0        21        Fort Stevenson State Park  ...   0.000284   0.135641
1        22           Beaver Lake State Park  ...   0.000129   0.080067
2        23  Fort Abraham Lincoln State Park  ...   0.000399   0.119868
3        24           Fort Ransom State Park  ...   0.000444   0.128733
4        25        Grahams Island State Park  ...   0.000469   0.125546

[5 rows x 6 columns]

In [5]:
#4)Describe the data with all features.
print('The features of the data is')
print(df.columns)

The features of the data is
Index(['OBJECTID', 'UNIT_NAME', 'DESCRIPTION', 'ACRES', 'SHAPE.AREA',
       'SHAPE.LEN'],
      dtype='object')


In [7]:
#5)Find the total count of missing values for each feature.
print('The total count of missing values for each feature are')
df.isnull().sum()

The total count of missing values for each feature are


OBJECTID       0
UNIT_NAME      0
DESCRIPTION    0
ACRES          0
SHAPE.AREA     0
SHAPE.LEN      0
dtype: int64

In [8]:
#6)Display all the unique values from the 'DESCRIPTION’ column.
print('The unique values from the DESCRIPTION are')
df.DESCRIPTION.unique()

The unique values from the DESCRIPTION are


array(['State Park', 'Interpretive Center', 'State Recreation Area',
       'State Natural Area', 'State Nature Preserve'], dtype=object)

In [10]:
#7)Create a grouped table usin 'DESCRIPTION' as the grouping columns with the means of all the other columns.
print('Mean of all the values in the DESCRIPTION are ')
df.groupby(['DESCRIPTION']).mean()

Mean of all the values in the DESCRIPTION are 


OBJECTID        ACRES  SHAPE.AREA  SHAPE.LEN
DESCRIPTION                                                         
Interpretive Center    29.000000    14.710000    0.000007   0.016774
State Natural Area     39.000000   219.615000    0.000105   0.077137
State Nature Preserve  39.500000    84.095000    0.000041   0.037175
State Park             28.538462  1168.668462    0.000567   0.150326
State Recreation Area  38.285714   326.934286    0.000162   0.078135

In [12]:
#8)Generate a random sample of 10 rows from the data.
print('random sample of 10 rows are')
df.sample(n=10)


random sample of 10 rows are


OBJECTID                            UNIT_NAME  ... SHAPE.AREA  SHAPE.LEN
7         28           Lewis and Clark State Park  ...   0.000256   0.130420
24        42  Pelican Point State Recreation Area  ...   0.000013   0.026357
8         29  Lewis and Clark Interpretive Center  ...   0.000007   0.016774
3         24               Fort Ransom State Park  ...   0.000444   0.128733
0         21            Fort Stevenson State Park  ...   0.000284   0.135641
16        37           Elkhorn State Natural Area  ...   0.000127   0.067082
10        31           Little Missouri State Park  ...   0.003136   0.313756
15        34            Lake Sakakawea State Park  ...   0.000357   0.191806
2         23      Fort Abraham Lincoln State Park  ...   0.000399   0.119868
14        33              Turtle River State Park  ...   0.000378   0.145220

[10 rows x 6 columns]

In [19]:
#9)Add a Feature called 'New_feature' to the new Dataset and Add Random float Values in between 0 and 1 using Numpy
df['New_feature']=np.random.rand(25)
print('Adding new feature to the data set')
df

Adding new feature to the data set


OBJECTID  ... New_feature
0         21  ...    0.128700
1         22  ...    0.535441
2         23  ...    0.160379
3         24  ...    0.942490
4         25  ...    0.269228
5         26  ...    0.880483
6         27  ...    0.689905
7         28  ...    0.502537
8         29  ...    0.478787
9         30  ...    0.423349
10        31  ...    0.765589
11        32  ...    0.470336
12        35  ...    0.009690
13        36  ...    0.896476
14        33  ...    0.991554
15        34  ...    0.905692
16        37  ...    0.148791
17        38  ...    0.777806
18        39  ...    0.257502
19        40  ...    0.172665
20        41  ...    0.885037
21        43  ...    0.809153
22        44  ...    0.260775
23        45  ...    0.038229
24        42  ...    0.386421

[25 rows x 7 columns]

In [18]:
#10) Replace zero value of column 'OBJECTID' with mean value permanently.
m=df['OBJECTID'].mean()
print('Replacung zero values of column OBJECTED with mean value of OBJECTED')
df.OBJECTID.fillna(m)
df

Replacung zero values of column OBJECTED with mean value of OBJECTED


OBJECTID  ... New_feature
0         21  ...    0.392150
1         22  ...    0.173889
2         23  ...    0.731997
3         24  ...    0.185361
4         25  ...    0.511525
5         26  ...    0.841072
6         27  ...    0.204251
7         28  ...    0.965479
8         29  ...    0.622839
9         30  ...    0.348168
10        31  ...    0.266035
11        32  ...    0.582331
12        35  ...    0.439887
13        36  ...    0.905495
14        33  ...    0.156809
15        34  ...    0.985295
16        37  ...    0.919026
17        38  ...    0.035899
18        39  ...    0.248722
19        40  ...    0.881411
20        41  ...    0.753681
21        43  ...    0.292866
22        44  ...    0.507372
23        45  ...    0.325036
24        42  ...    0.122934

[25 rows x 7 columns]