In [5]:
#1) Generate an array of zeroes using inbuilt numpy function.
a=[['0','0','0'],['0','0','0']]
print(a)

[['0', '0', '0'], ['0', '0', '0']]


In [6]:
#2) Run the given code and find the dot product of both arrays.
import numpy as np
a = np.random.randint(2,10, (3,4))
b = np.random.randint(2,10, (4,3))
print(a)
print(b)
a.dot(b)

[[3 2 5 6]
 [4 2 2 7]
 [6 4 5 3]]
[[6 8 4]
 [8 7 4]
 [8 5 6]
 [2 9 5]]


array([[ 86, 117,  80],
       [ 70, 119,  71],
       [114, 128,  85]])

In [ ]:
#3)Read the csv file provided using pandas and display the first 5 entries
import pandas as pd
df=pd.read_csv('/content/data.csv')
df.head()

In [12]:
#4)Describe the data with all features.
print(df.columns)

Index(['OBJECTID', 'UNIT_NAME', 'DESCRIPTION', 'ACRES', 'SHAPE.AREA',
       'SHAPE.LEN'],
      dtype='object')


In [ ]:
#5)Find the total count of missing values for each feature.
df.isnull().sum()

In [15]:
#6)Display all the unique values from the 'DESCRIPTION’ column.
df.DESCRIPTION.unique()

array(['State Park', 'Interpretive Center', 'State Recreation Area',
       'State Natural Area', 'State Nature Preserve'], dtype=object)

In [ ]:
#7)Create a grouped table usin 'DESCRIPTION' as the grouping columns with the means of all the other columns.
df.groupby(['DESCRIPTION']).mean()

In [ ]:
#8)Generate a random sample of 10 rows from the data.
df.sample(n=10)


In [ ]:
#9)Add a Feature called 'New_feature' to the new Dataset and Add Random float Values in between 0 and 1 using Numpy
df['New_feature']=np.random.rand(25)
df

In [ ]:
#10) Replace zero value of column 'OBJECTID' with mean value permanently.
m=df['OBJECTID'].mean()
df.OBJECTID.fillna(m)
